import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; //Estilos globales
import Link from "next/link";
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';
import { EditorProvider } from '@/context/editorContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        
        <div id="globalNavbar">
          <Link href={'/usuarios'}>Usuarios</Link>
          <Link href={'/contacto'}>Contacto</Link>
          <Link href={'/articulos'}>Articulos</Link>
          <Link href={'/podcast'}>Podcasts</Link>

        </div>
        <EditorProvider>
          <MantineProvider>{children}</MantineProvider>
          </EditorProvider>

      </body>
    </html>
  );
}
